<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Event — HoneyBee</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&family=Dancing+Script:wght@700&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />
  <link rel="stylesheet" href="{{ asset('css/event.css') }}" />
</head>
<body>

<!-- ===================== HEADER ===================== -->
<header class="header" id="header">
  <div class="header-inner">
    <div class="logo-wrap">
      <img src="{{ asset('images/logo.png') }}" alt="HoneyBee Gifts & Designs Logo" class="logo-img"/>
      <div class="logo-text">
        <span class="brand-name">Event<span class="accent"> Celebration</span></span>
      </div>
    </div>

    <nav class="nav" id="nav">
      <a href="#home" class="nav-link">Home</a>
      <a href="#events" class="nav-link">Events</a>
      <a href="#gallery" class="nav-link">Gallery</a>
      <a href="#contact" class="nav-link">Contact</a>
    </nav>

    <div class="header-actions">
      <button class="btn btn-cart" onclick="toggleCart()">
        <svg width="28" height="28" viewBox="0 0 24 24" fill="none"
             stroke="currentColor" stroke-width="2.5"
             stroke-linecap="round" stroke-linejoin="round">
            <circle cx="9" cy="20" r="1"></circle>
            <circle cx="18" cy="20" r="1"></circle>
            <path d="M1 1h4l2.68 13.39A2 2 0 0 0 9.64 16H19a2 2 0 0 0 2-1.64L23 6H6"></path>
        </svg>
        <span id="cart-count">0</span>
      </button>
      <button class="hamburger" id="hamburger" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="nav">
        <span></span>
        <span></span>
        <span></span>
      </button>
    </div>
  </div>
</header>

<!-- ===================== HERO ===================== -->
<section class="hero" id="home">
  <div class="hero-bg-pattern"></div>
  <div class="hero-content">
    <p class="hero-eyebrow">✦ Available for Jaffna District ✦</p>
     <h1 class="hero-heading">Creative Event Designs<br><span class="accent">for Every Occasion</span></h1>
    <p class="hero-eyebrow">Our events are memorable gatherings filled with thoughtful design, meaningful interactions, and inspiring experiences.</p>
  </div>
  <div class="hero-scroll-hint">
    <span>Scroll to explore</span>
    <i class="fas fa-chevron-down"></i>
  </div>
</section>

<!-- ===================== SEARCH ===================== -->
<section class="search-section" id="search">
  <div class="container">
    <div class="search-wrap">
      <i class="fas fa-search search-icon"></i>
      <input type="text" id="searchInput" placeholder="Search event categories… e.g. Wedding, Birthday" class="search-input" oninput="filterEvents()"/>
      <button class="search-clear" onclick="clearSearch()" id="clearBtn" style="display:none"><i class="fas fa-times"></i></button>
    </div>
    <p class="search-hint" id="searchHint"></p>
  </div>
</section>

<!-- ===================== EVENTS CATEGORIES ===================== -->
<section class="events-section" id="events">
  <div class="container">
    <div class="section-header">
      <span class="section-eyebrow">What We Do</span>
      <h2 class="section-title">Event Categories</h2>
      <p class="section-desc">From intimate gatherings to grand celebrations — we design every moment with care.</p>
    </div>
    <div class="events-grid" id="eventsGrid">
      <!-- Cards generated by JS -->
    </div>
    <p class="no-results" id="noResults" style="display:none">No event categories match your search. Try another keyword.</p>
  </div>
</section>

<!-- ===================== WHY CHOOSE US ===================== -->
<section class="why-section" id="why">
  <div class="container">
    <div class="section-header light">
      <span class="section-eyebrow">Our Promise</span>
      <h2 class="section-title">Why Choose HoneyBee?</h2>
    </div>
    <div class="features-grid">
      <div class="feature-card">
        <div class="feature-icon"><i class="fas fa-calendar-check"></i></div>
        <h3>Professional Planning</h3>
        <p>End-to-end event planning handled by our expert team — zero stress for you.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon"><i class="fas fa-palette"></i></div>
        <h3>Creative Decorations</h3>
        <p>Bespoke décor themes tailored to your vision, personality, and budget.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon"><i class="fas fa-star"></i></div>
        <h3>Quality Service</h3>
        <p>We deliver nothing short of excellence — every time, for every event.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon"><i class="fas fa-tags"></i></div>
        <h3>Affordable Packages</h3>
        <p>Premium events shouldn't break the bank. Our packages suit every budget.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon"><i class="fas fa-users"></i></div>
        <h3>Experienced Team</h3>
        <p>Our seasoned designers and planners bring years of creative expertise.</p>
      </div>
      <div class="feature-card">
        <div class="feature-icon"><i class="fas fa-clock"></i></div>
        <h3>On-Time Delivery</h3>
        <p>We respect your schedule. Setup is always complete before your guests arrive.</p>
      </div>
    </div>
  </div>
</section>

<!-- ===================== GALLERY ===================== -->
<section class="gallery-section" id="gallery">
  <div class="container">
    <div class="section-header">
      <span class="section-eyebrow">Our Work</span>
      <h2 class="section-title">Gallery</h2>
      <p class="section-desc">A glimpse into the magical moments we've created across Jaffna.</p>
    </div>
    <div class="gallery-grid" id="galleryGrid">
      <div class="gallery-item g-tall"><div class="gallery-overlay"><span>Wedding Moments</span></div></div>
      <div class="gallery-item"><div class="gallery-overlay"><span>Birthday Magic</span></div></div>
      <div class="gallery-item"><div class="gallery-overlay"><span>Baby Shower Bliss</span></div></div>
      <div class="gallery-item g-wide"><div class="gallery-overlay"><span>Corporate Elegance</span></div></div>
      <div class="gallery-item"><div class="gallery-overlay"><span>Graduation Pride</span></div></div>
      <div class="gallery-item"><div class="gallery-overlay"><span>Cultural Festivities</span></div></div>
      <div class="gallery-item g-tall"><div class="gallery-overlay"><span>Outdoor Events</span></div></div>
      <div class="gallery-item"><div class="gallery-overlay"><span>Religious Ceremonies</span></div></div>
    </div>
  </div>
</section>

<!-- ===================== INQUIRY ===================== -->
<section class="inquiry-section" id="inquiry">
  <div class="container">
    <div class="inquiry-grid">
      <div class="inquiry-info">
        <span class="section-eyebrow">Get In Touch</span>
        <h2 class="section-title">Book Your Dream Event</h2>
        <p>Ready to make memories? Reach out and our team will get back to you within 24 hours.</p>
        <div class="inquiry-actions">
          <button class="btn-primary" onclick="document.getElementById('inquiryForm').scrollIntoView({behavior:'smooth'})">
            <i class="fas fa-calendar-plus"></i> Book Event
          </button>
          <a href="https://wa.me/94XXXXXXXXX?text=Hello%20HoneyBee%20Events!%20I%27d%20like%20to%20book%20an%20event." target="_blank" class="btn-whatsapp">
            <i class="fab fa-whatsapp"></i> WhatsApp Us
          </a>
        </div>
      </div>

      <form class="inquiry-form" id="inquiryForm" onsubmit="submitInquiry(event)">
        <h3>Send an Inquiry</h3>
        <div class="form-row">
          <div class="form-group">
            <label>Your Name</label>
            <input type="text" placeholder="e.g. Priya Nair" required/>
          </div>
          <div class="form-group">
            <label>Phone Number</label>
            <input type="tel" placeholder="+94 XX XXX XXXX" required/>
          </div>
        </div>
        <div class="form-group">
          <label>Email Address</label>
          <input type="email" placeholder="priya@example.com"/>
        </div>
        <div class="form-row">
          <div class="form-group">
            <label>Event Type</label>
            <select required>
              <option value="">Select category</option>
              <option>Birthday Party</option>
              <option>Wedding</option>
              <option>Engagement</option>
              <option>Anniversary</option>
              <option>Baby Shower</option>
              <option>Corporate Event</option>
              <option>School Event</option>
              <option>Cultural Event</option>
              <option>Religious Event</option>
              <option>Family Gathering</option>
              <option>Outdoor Event</option>
              <option>Graduation</option>
              <option>Customized Event</option>
            </select>
          </div>
          <div class="form-group">
            <label>Event Date</label>
            <input type="date" required/>
          </div>
        </div>
        <div class="form-group">
          <label>Message</label>
          <textarea rows="4" placeholder="Tell us about your vision…"></textarea>
        </div>
        <button type="submit" class="btn-primary full-width">Send Inquiry <i class="fas fa-paper-plane"></i></button>
      </form>
    </div>
  </div>
</section>

<!-- ===================== CONTACT ===================== -->
<section class="contact-section" id="contact">
  <div class="container">
    <div class="contact-grid">
      <div class="contact-item">
        <div class="contact-icon"><i class="fas fa-phone-alt"></i></div>
        <h4>Phone</h4>
        <p>+94 0766975438</p>
      </div>
      <div class="contact-item">
        <div class="contact-icon"><i class="fas fa-envelope"></i></div>
        <h4>Email</h4>
        <p>Honeybeeevents99@gmail.com</p>
      </div>
      <div class="contact-item">
        <div class="contact-icon"><i class="fas fa-map-marker-alt"></i></div>
        <h4>Address</h4>
        <p>190, Sir. Pom Ramanathan Road,<br/>Thirunelvely, Jaffna</p>
      </div>
      <div class="contact-item">
        <div class="contact-icon"><i class="fas fa-share-alt"></i></div>
        <h4>Follow Us</h4>
        <div class="social-links d-flex flex-wrap justify-content-center gap-2 gap-sm-3">
          <a href="#" class="btn btn-outline-warning rounded-circle social-link social-facebook" aria-label="Follow us on Facebook" title="Facebook">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a href="#" class="btn btn-outline-warning rounded-circle social-link social-instagram" aria-label="Follow us on Instagram" title="Instagram">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="#" class="btn btn-outline-warning rounded-circle social-link social-youtube" aria-label="Subscribe on YouTube" title="YouTube">
            <i class="fab fa-youtube"></i>
          </a>
          <a href="https://wa.me/94766975438?text=Hello%20HoneyBee%20Events!%20I%27d%20like%20to%20book%20an%20event." target="_blank" rel="noopener noreferrer" class="btn btn-outline-warning rounded-circle social-link social-whatsapp" aria-label="Chat with us on WhatsApp" title="WhatsApp">
            <i class="fab fa-whatsapp"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- ===================== FOOTER ===================== -->
<footer class="footer">
  <div class="container">
    <div class="footer-grid">
      <div class="footer-brand">
        <img src="{{ asset('images/logo.png') }}" alt="HoneyBee" class="footer-logo"/>
        <p>Creating unforgettable event experiences across Jaffna District since 2018.</p>
      </div>
      <div class="footer-links">
        <h5>Quick Links</h5>
        <a href="#home">Home</a>
        <a href="#events">Events</a>
        <a href="#gallery">Gallery</a>
        <a href="#inquiry">Book Event</a>
        <a href="#contact">Contact</a>
      </div>
      <div class="footer-links">
        <h5>Event Types</h5>
        <a href="#events">Weddings</a>
        <a href="#events">Birthdays</a>
        <a href="#events">Engagements</a>
        <a href="#events">Corporate</a>
        <a href="#events">Religious</a>
      </div>
      <div class="footer-contact">
        <h5>Contact Info</h5>
        <ul style="list-style:none;padding:0;">
          <li style="margin-bottom: .5rem;"><i class="fas fa-phone-alt"></i> +94  0766975438</li>
          <li style="margin-bottom: .5rem;"><i class="fas fa-envelope"></i> Honeybeeevents99@gmail.com</li>
          <li><i class="fas fa-map-marker-alt"></i> Jaffna, Sri Lanka</li>
        </ul>
      </div>
    </div>
    <div class="footer-bottom">
      <p>&copy; 2025 HoneyBee Gifts &amp; Designs. All rights reserved.</p>
      <p>Crafted with <i class="fas fa-heart" style="color:#F5A623"></i> in Jaffna</p>
    </div>
  </div>
</footer>


<!-- ===================== EVENT DETAIL MODAL ===================== -->
<div class="modal-overlay" id="detailOverlay" onclick="closeDetailIfOutside(event)">
  <div class="detail-modal">
    <button class="admin-close" onclick="closeDetail()"><i class="fas fa-times"></i></button>
    <div class="detail-img-wrap"><div class="detail-img-placeholder" id="detailImgIcon"></div></div>
    <div class="detail-body">
      <span class="detail-tag" id="detailTag"></span>
      <h2 id="detailName"></h2>
      <p class="detail-price" id="detailPrice"></p>
      <p id="detailDesc"></p>
      <ul class="detail-features" id="detailFeatures"></ul>
      <div class="detail-actions">
        <a href="https://wa.me/94XXXXXXXXX" target="_blank" class="btn-whatsapp"><i class="fab fa-whatsapp"></i> Book via WhatsApp</a>
        <button class="btn-primary" onclick="closeDetail(); document.getElementById('inquiry').scrollIntoView({behavior:'smooth'})">Book Now</button>
      </div>
    </div>
  </div>
</div>

<!-- ===================== TOAST ===================== -->
<div class="toast" id="toast"></div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{ asset('js/event.js') }}"></script>
</body>
</html>
