@extends('layouts.staff')
@section('title', 'Dashboard')
@section('content')
<style>.welcome{background:linear-gradient(135deg,#1a1a1a,#303030);color:#fff;border-left:5px solid #f5a623}.welcome h1{font-family:Georgia,serif;color:#f5a623}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.metric{text-align:center}.metric i{display:grid;place-items:center;margin:auto auto 10px;width:48px;height:48px;border-radius:50%;background:#fff3d6;color:#f5a623;font-size:20px}.metric h2{margin:0;font-size:28px}@media(max-width:700px){.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:420px){.metrics{grid-template-columns:1fr}}</style>
<div class="page-head"><h1>Staff <span>Dashboard</span></h1><span class="text-muted">{{ $staff->full_name }}</span></div>
<section class="honey-card welcome mb-4"><h1 class="h2">Welcome back, {{ $staff->full_name }}!</h1><p class="mb-0 text-white-50">Your operational overview for orders, products, and gallery content.</p></section>
<section class="metrics mb-4">@foreach([['fa-receipt',$totalOrders,'Total Orders'],['fa-clock',$pendingOrders,'Pending Orders'],['fa-spinner',$processingOrders,'Processing Orders'],['fa-circle-check',$completedOrders,'Completed Orders'],['fa-box-open',$totalProducts,'Total Products'],['fa-images',$galleryItems,'Gallery Items']] as [$icon,$value,$label])<div class="honey-card metric"><i class="fa-solid {{ $icon }}"></i><h2>{{ $value }}</h2><p class="mb-0 text-muted">{{ $label }}</p></div>@endforeach</section>
<div class="row g-4"><div class="col-lg-7"><section class="honey-card h-100"><div class="d-flex justify-content-between mb-3"><h2 class="h4 mb-0">Recent Orders</h2><a href="{{ route('staff.orders.index') }}" class="btn btn-sm btn-honey">View all</a></div>@forelse($recentOrders as $order)<div class="d-flex justify-content-between align-items-center border-top py-3"><div><strong>#{{ $order->order_id }} — {{ $order->customer?->full_name ?? 'Unknown customer' }}</strong><br><small class="text-muted">{{ $order->order_date?->format('d M Y') ?? 'No date' }} · {{ $order->items->count() }} item(s)</small></div><span class="badge-status status-{{ $order->status }}">{{ ucfirst($order->status) }}</span></div>@empty <p class="text-muted mb-0">No orders yet.</p>@endforelse</section></div>
<div class="col-lg-5"><section class="honey-card mb-4"><h2 class="h4">Recently Added Products</h2>@forelse($recentProducts as $product)<div class="border-top py-2"><strong>{{ $product->name }}</strong><br><small class="text-muted">{{ $product->type }} · {{ $product->created_at?->format('d M Y') }}</small></div>@empty <p class="text-muted mb-0">No products yet.</p>@endforelse</section><section class="honey-card"><h2 class="h4">Latest Gallery Uploads</h2>@forelse($recentGallery as $image)<div class="border-top py-2"><strong>{{ $image->title ?: 'Untitled image' }}</strong><br><small class="text-muted">{{ $image->category }}</small></div>@empty <p class="text-muted mb-0">No gallery items yet.</p>@endforelse</section></div></div>
@endsection
